### ISSUE TITLE
Question: .env oder .now-secrets for sensibel data?

### ISSUE THREAD

**Issue by dev7ch** [14nrv/buefy-shop#18]
First of all, thank you for your cool usage example.

if i use `.now-secrets.json` file it didn´t work, with .env file it is working almost (no errors, no products)

Everthing works fine in dev mode locally, but somehow i didn´t get products from my firebase realtime DB.

I imported the __tests__/__mocks__/products.json to my firebase relatime DB.

Here is the deployed example from your application:
https://testshop-buefy.firebaseapp.com/ 

Usally there shouldn´t be an .env file needed, correct?

Do you have an idea why no products and no errors are shown?

Best Regards from Basel

**Comment by 14nrv** [comment]
Hey @dev7ch,

Thanks for using it :)

With .env file it should works on dev env (due to nuxt.config.js).
For the production env, you can remove this condition "isNotProdEnv && ..." or put ENV variables directly inside Firebase I think.

For testing Firebase, you can put directly here the ENV values here : /firebase-setup/config.js.
Usually, using a .env is a good practice I think.

In fact if I resume you have the choice, you can put env variables here:
- On dev env : .bashrc  or .env (or firebase-setup/config.js just for testing)
- On prod : .env (without "isNotProdEnv &&") or directly inside Firebase or on your CI

I hope it will help you

**Comment by dev7ch** [comment]
thank you for the detailed reply 👍

**Comment by 14nrv** [comment]
Hi @dev7ch 

Why you reopened this closed issue ? Do you need help with the .env ?

**Comment by dev7ch** [comment]
@14nrv sorry it wasn`t on purpose, sorry for that
